name: e2e

on:
  workflow_dispatch: {}  # manual trigger

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      # has python & browsers for Playwright; version matches pin in pyproject.toml
      image: mcr.microsoft.com/playwright/python:v1.55.0-noble

    env:
      # Runtime config
      BASE_URL: ${{ vars.BASE_URL }}
      USER_TIER2_USERNAME: ${{ secrets.USER_TIER2_USERNAME }}
      USER_TIER2_PASSWORD: ${{ secrets.USER_TIER2_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies (Poetry)
        run: poetry install --no-interaction --no-ansi --only test

      - name: Run pytest (generate HTML report)
        run: |
          mkdir -p playwright-report
          poetry run pytest

      - name: Upload HTML report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          overwrite: true
          retention-days: 30

  deploy-pages:
    name: Publish report to GitHub Pages
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:

      - name: Install jq (for reading metadata)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Checkout gh-pages branch (if exists)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ghp           # checkout into ./ghp; if branch doesn't exist, this step still creates the folder

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: _report_in/

      - name: Stage site (preserve history, add new run, rebuild index)
        run: |
          set -euo pipefail

          mkdir -p public
          if [ -d ghp ]; then
            rsync -a --delete --exclude='.git' ghp/ public/
          fi

          # Add this run under runs/run-<run_number>/
          run_dir="public/runs/run-${{ github.run_number }}"
          mkdir -p "$run_dir"
          mv _report_in/report.html "$run_dir/report.html"

          # Write per-run metadata (status + UTC ISO timestamp + link back to workflow run)
          printf '%s\n' \
            '{' \
            '  "run": '"${{ github.run_number }}"',' \
            '  "status": "'"${{ needs.tests.result }}"'",' \
            '  "datetime": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",' \
            '  "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"' \
            '}' > "$run_dir/meta.json"


          # Rebuild a static index.html listing all runs (newest first)
          mkdir -p public/runs
          {
            echo '<!doctype html><meta charset="utf-8"><title>E2E Reports</title>'
            echo '<style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:2rem}h1{margin:.2rem 0}.muted{color:#666}ul{line-height:1.8}li{margin:.25rem 0}.badge{display:inline-block;width:.6rem;height:.6rem;border-radius:50%;vertical-align:baseline;margin-right:.4rem}.ok{background:#22c55e}.fail{background:#ef4444}.skip{background:#9ca3af}</style>'
            echo '<h1>E2E Reports</h1><p class="muted">History of published runs.</p><ul>'

            if [ -d public/runs ]; then
              # list run-* dirs, sort numerically desc on the run number
              find public/runs -maxdepth 1 -type d -name 'run-*' -printf '%f\n' \
              | sed -E 's/run-([0-9]+)/\1 &/' \
              | sort -nr \
              | cut -d' ' -f2 \
              | while read -r d; do
                  status="unknown"; when=""; badge_class="skip"
                  if [ -f "public/runs/$d/meta.json" ]; then
                    status=$(jq -r '.status // "unknown"' "public/runs/$d/meta.json")
                    when=$(jq -r '.datetime // ""' "public/runs/$d/meta.json")
                  fi
                  case "$status" in
                    success) badge_class="ok" ;;
                    failure|cancelled|timed_out) badge_class="fail" ;;
                    *) badge_class="skip" ;;
                  esac
                  label="$d"
                  if [ -n "$when" ]; then
                    label="$d — $when"
                  fi
                  echo "<li><span class='badge $badge_class'></span><a href=\"runs/$d/report.html\">$label</a></li>"
                done
            fi
            echo '</ul>'
          } > public/index.html

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
          commit_message: "Publish report for run ${{ github.run_number }}"
